CREATE PROCEDURE [dbo].[SPW_INSERT_DDAY_HOURLY_SALES]
    @list APP_DDAY_HOURLY_SALES_TYPE READONLY
AS
BEGIN
  
    INSERT INTO APP_DDAY_HOURLY_SALES (DDES_SITE_ID,
DDES_BUSINESS_DT,
DDES_SALES_TM,
DDES_MCDE_SIR_ID,
DDES_MVAL_SIR_ID,
DDES_LLVR_SIR_ID,
DDES_SALES_PROD_AM,
DDES_SALES_NON_PROD_AM,
DDES_EAT_IN_TAC_QY,
DDES_TAKE_OUT_TAC_QY,
DDES_EAT_IN_SALES_AM,
DDES_TAKE_OUT_SALES_AM,
DDES_DISCOUNT_IN_TAC_QY,
DDES_DISCOUNT_OUT_TAC_QY,
DDES_DISCOUNT_IN_SALES_AM,
DDES_DISCOUNT_OUT_SALES_AM,
DDES_CREW_HOURS_WORKED,
DDES_PROCESS_DT)
    SELECT *
    FROM @list;
    
END
