create database McDashboard_Devl
use McDashboard_Devl

select * from APP_DDAY_HOURLY_PMX order by DDMX_PROD_ID
delete from APP_DDAY_HOURLY_PMX where DDMX_BUSINESS_DT='2018-10-03 00:00:00'

CREATE TABLE [dbo].[APP_DDAY_HOURLY_SALES](	
    [DDES_ID] [int] IDENTITY(1,1) NOT NULL,
	[DDES_SITE_ID] [smallint] NOT NULL,
	[DDES_BUSINESS_DT] [smalldatetime] NOT NULL,
	[DDES_SALES_TM] [smallint] NOT NULL,
	[DDES_MCDE_SIR_ID] [smallint] NOT NULL,
	[DDES_MVAL_SIR_ID] [smallint] NOT NULL,
	[DDES_LLVR_SIR_ID] [smallint] NOT NULL,
	[DDES_SALES_PROD_AM] [money] NULL,
	[DDES_SALES_NON_PROD_AM] [money] NULL,
	[DDES_EAT_IN_TAC_QY] [smallint] NULL,
	[DDES_TAKE_OUT_TAC_QY] [smallint] NULL,
	[DDES_EAT_IN_SALES_AM] [money] NULL,
	[DDES_TAKE_OUT_SALES_AM] [money] NULL,
	[DDES_DISCOUNT_IN_TAC_QY] [smallint] NULL,
	[DDES_DISCOUNT_OUT_TAC_QY] [smallint] NULL,
	[DDES_DISCOUNT_IN_SALES_AM] [money] NULL,
	[DDES_DISCOUNT_OUT_SALES_AM] [money] NULL,
	[DDES_CREW_HOURS_WORKED] [numeric](12, 3) NULL,
	[DDES_PROCESS_DT] [datetime] NULL
) ON [PRIMARY]	

CREATE TABLE [dbo].[APP_DDAY_HOURLY_PMX](	
    [DDMX_ID] [int] IDENTITY(1,1) NOT NULL,
	[DDMX_SITE_ID] [smallint] NOT NULL,
	[DDMX_BUSINESS_DT] [smalldatetime] NOT NULL,
	[DDMX_PROD_ID] [int] NOT NULL,
	[DDMX_SALES_TM] [smallint] NOT NULL,
	[DDMX_MCDE_SIR_ID] [tinyint] NOT NULL,
	[DDMX_MVAL_SIR_ID] [tinyint] NOT NULL,
	[DDMX_LLVR_SIR_ID] [tinyint] NOT NULL,
	[DDMX_EAT_IN_QY] [smallint] NOT NULL,
	[DDMX_TAKE_OUT_QY] [smallint] NOT NULL,
	[DDMX_PROMO_IN_QY] [smallint] NULL,
	[DDMX_PROMO_OUT_QY] [smallint] NULL,
	[DDMX_DISCOUNT_IN_QY] [smallint] NULL,
	[DDMX_DISCOUNT_OUT_QY] [smallint] NULL,
	[DDMX_EMPLOYEE_MEAL_QY] [smallint] NULL,
	[DDMX_MGR_MEAL_QY] [smallint] NULL,
	[DDMX_EMPLOYEE_MEAL_AM] [money] NULL,
	[DDMX_CA_IN_AM] [smallmoney] NULL,
	[DDMX_CA_OUT_AM] [smallmoney] NULL,
	[DDMX_PROCESS_DT] [datetime] NOT NULL,
) ON [PRIMARY]	

CREATE TABLE [dbo].[RFU_MCDE](
	[MCDE_SIR_ID] [int] NOT NULL,
	[MCDE_PODSHORT] [varchar](255) NOT NULL,
	[MCDE_SIGNIFICATION] [varchar](500) NOT NULL,
	PRIMARY KEY(MCDE_SIR_ID)
) ON [PRIMARY]

CREATE TABLE [dbo].[RFU_MVAL](
	[MVAL_SIR_ID] [int] NOT NULL,
	[MVAL_PODSHORT] [varchar](255) NOT NULL,
	[MVAL_SIGNIFICATION] [varchar](500) NOT NULL,
	PRIMARY KEY(MVAL_SIR_ID)
) ON [PRIMARY]

CREATE TABLE [dbo].[RFU_LLVR](
	[LLVR_SIR_ID] [int] NOT NULL,
	[LLVR_PODSHORT] [varchar](255) NOT NULL,
	[LLVR_SIGNIFICATION] [varchar](500) NOT NULL,
	PRIMARY KEY(LLVR_SIR_ID)
) ON [PRIMARY]

CREATE TABLE[dbo].[RFU_POD_SIR_ID](
[PDID_PODSHORT][varchar](255) NOT NULL,
[PDID_MCDE_SIR_ID][int] NOT NULL,
[PDID_MVAL_SIR_ID][int] NOT NULL,
[PDID_LLVR_SIR_ID][int] NOT NULL,
PRIMARY KEY(PDID_PODSHORT)
) ON [PRIMARY]

select * from RFU_POD_SIR_ID
INSERT [dbo].[RFU_POD_SIR_ID](PDID_PODSHORT,PDID_MCDE_SIR_ID,PDID_MVAL_SIR_ID,PDID_LLVR_SIR_ID) VALUES ( 'FC',	1,	1,	1);
INSERT [dbo].[RFU_POD_SIR_ID](PDID_PODSHORT,PDID_MCDE_SIR_ID,PDID_MVAL_SIR_ID,PDID_LLVR_SIR_ID) VALUES ( 'DT',	1,	2,	2);
INSERT [dbo].[RFU_POD_SIR_ID](PDID_PODSHORT,PDID_MCDE_SIR_ID,PDID_MVAL_SIR_ID,PDID_LLVR_SIR_ID) VALUES ( 'CSO',	3,	9,	3);
INSERT [dbo].[RFU_POD_SIR_ID](PDID_PODSHORT,PDID_MCDE_SIR_ID,PDID_MVAL_SIR_ID,PDID_LLVR_SIR_ID) VALUES ( 'MCC',	4,	3,	4);
INSERT [dbo].[RFU_POD_SIR_ID](PDID_PODSHORT,PDID_MCDE_SIR_ID,PDID_MVAL_SIR_ID,PDID_LLVR_SIR_ID) VALUES ( 'DLV',	6,	10,	3);
INSERT [dbo].[RFU_POD_SIR_ID](PDID_PODSHORT,PDID_MCDE_SIR_ID,PDID_MVAL_SIR_ID,PDID_LLVR_SIR_ID) VALUES ( 'CK',	6,	10,	3);
INSERT [dbo].[RFU_POD_SIR_ID](PDID_PODSHORT,PDID_MCDE_SIR_ID,PDID_MVAL_SIR_ID,PDID_LLVR_SIR_ID) VALUES ( 'MCE',	1,	5,	5);
INSERT [dbo].[RFU_POD_SIR_ID](PDID_PODSHORT,PDID_MCDE_SIR_ID,PDID_MVAL_SIR_ID,PDID_LLVR_SIR_ID) VALUES ( 'CKD',	6,	8,	8);

CREATE TABLE [dbo].[TRA_LOG](
	[LOG_ID] [int] IDENTITY(1,1) NOT NULL,
	[LOG_DATE] [datetime] NOT NULL,
	[LOG_RESTAURANTID] [varchar](255) NOT NULL,
	[LOG_DUREE] [varchar](255) NOT NULL,
	[LOG_THREAD] [varchar](255) NOT NULL,
	[LOG_LEVEL] [varchar](50) NOT NULL,
	[LOG_LOGGER] [varchar](255) NOT NULL,
	[LOG_MESSAGE] [varchar](4000) NOT NULL,
	[LOG_PROCESSLOGID] [varchar](50) NOT NULL,
	[LOG_EXCEPTION] [varchar](2000) NULL
) ON [PRIMARY]

INSERT [dbo].[RFU_MCDE]([MCDE_PODSHORT],[MCDE_SIGNIFICATION],[MCDE_SIR_ID]) VALUES ('NA','NA',0)
INSERT [dbo].[RFU_MCDE]([MCDE_PODSHORT],[MCDE_SIGNIFICATION],[MCDE_SIR_ID]) VALUES ('CK','Cold-Kiosk',1);
INSERT [dbo].[RFU_MCDE]([MCDE_PODSHORT],[MCDE_SIGNIFICATION],[MCDE_SIR_ID]) VALUES ('MCC','McCafe',2);
INSERT [dbo].[RFU_MCDE]([MCDE_PODSHORT],[MCDE_SIGNIFICATION],[MCDE_SIR_ID]) VALUES ('CSO','Customer Self-Ordering (Kiosk)',3);
INSERT [dbo].[RFU_MCDE]([MCDE_PODSHORT],[MCDE_SIGNIFICATION],[MCDE_SIR_ID]) VALUES ('HOT','Hand-held Order',4);

INSERT [dbo].[RFU_MVAL]([MVAL_PODSHORT],[MVAL_SIGNIFICATION],[MVAL_SIR_ID]) VALUES ('NA','NA',0);
INSERT [dbo].[RFU_MVAL]([MVAL_PODSHORT],[MVAL_SIGNIFICATION],[MVAL_SIR_ID]) VALUES ('FC','Front-Counter',1);
INSERT [dbo].[RFU_MVAL]([MVAL_PODSHORT],[MVAL_SIGNIFICATION],[MVAL_SIR_ID]) VALUES ('DT','Drive-Thru',2);
INSERT [dbo].[RFU_MVAL]([MVAL_PODSHORT],[MVAL_SIGNIFICATION],[MVAL_SIR_ID]) VALUES ('WT','Walk-Thru' ,3);
INSERT [dbo].[RFU_MVAL]([MVAL_PODSHORT],[MVAL_SIGNIFICATION],[MVAL_SIR_ID]) VALUES ('DLV','McDelivery',4);
INSERT [dbo].[RFU_MVAL]([MVAL_PODSHORT],[MVAL_SIGNIFICATION],[MVAL_SIR_ID]) VALUES ('MCC','McCafe',5);
INSERT [dbo].[RFU_MVAL]([MVAL_PODSHORT],[MVAL_SIGNIFICATION],[MVAL_SIR_ID]) VALUES ('MCE','McExpress'	,6);
INSERT [dbo].[RFU_MVAL]([MVAL_PODSHORT],[MVAL_SIGNIFICATION],[MVAL_SIR_ID]) VALUES ('CSO','Customer Self-Ordering (Kiosk)',7);

INSERT [dbo].[RFU_LLVR]([LLVR_PODSHORT],[LLVR_SIGNIFICATION],[LLVR_SIR_ID]) VALUES ('NA','NA',0);
INSERT [dbo].[RFU_LLVR]([LLVR_PODSHORT],[LLVR_SIGNIFICATION],[LLVR_SIR_ID]) VALUES ('FC','Front-Counter',1);
INSERT [dbo].[RFU_LLVR]([LLVR_PODSHORT],[LLVR_SIGNIFICATION],[LLVR_SIR_ID]) VALUES ('DT','Drive-Thru',2);
INSERT [dbo].[RFU_LLVR]([LLVR_PODSHORT],[LLVR_SIGNIFICATION],[LLVR_SIR_ID]) VALUES ('WT','Walk-Thru' ,3);
INSERT [dbo].[RFU_LLVR]([LLVR_PODSHORT],[LLVR_SIGNIFICATION],[LLVR_SIR_ID]) VALUES ('DLV','McDelivery',4);
INSERT [dbo].[RFU_LLVR]([LLVR_PODSHORT],[LLVR_SIGNIFICATION],[LLVR_SIR_ID]) VALUES ('MCC','McCafe',5);
INSERT [dbo].[RFU_LLVR]([LLVR_PODSHORT],[LLVR_SIGNIFICATION],[LLVR_SIR_ID]) VALUES ('MCE','McExpress',6);

CREATE TYPE [dbo].[APP_DDAY_HOURLY_PMX_TYPE] AS TABLE(	
	[DDMX_SITE_ID] [smallint] NOT NULL,
	[DDMX_BUSINESS_DT] [smalldatetime] NOT NULL,
	[DDMX_PROD_ID] [int] NOT NULL,
	[DDMX_SALES_TM] [smallint] NOT NULL,
	[DDMX_MCDE_SIR_ID] [tinyint] NOT NULL,
	[DDMX_MVAL_SIR_ID] [tinyint] NOT NULL,
	[DDMX_LLVR_SIR_ID] [tinyint] NOT NULL,
	[DDMX_EAT_IN_QY] [smallint] NOT NULL,
	[DDMX_TAKE_OUT_QY] [smallint] NOT NULL,
	[DDMX_PROMO_IN_QY] [smallint] NULL,
	[DDMX_PROMO_OUT_QY] [smallint] NULL,
	[DDMX_DISCOUNT_IN_QY] [smallint] NULL,
	[DDMX_DISCOUNT_OUT_QY] [smallint] NULL,
	[DDMX_EMPLOYEE_MEAL_QY] [smallint] NULL,
	[DDMX_MGR_MEAL_QY] [smallint] NULL,
	[DDMX_EMPLOYEE_MEAL_AM] [money] NULL,
	[DDMX_CA_IN_AM] [smallmoney] NULL,
	[DDMX_CA_OUT_AM] [smallmoney] NULL,
	[DDMX_PROCESS_DT] [datetime] NOT NULL
);

CREATE TYPE [dbo].[APP_DDAY_HOURLY_SALES_TYPE] AS TABLE(	
	[DDES_SITE_ID] [smallint] NOT NULL,
	[DDES_BUSINESS_DT] [smalldatetime] NOT NULL,
	[DDES_SALES_TM] [smallint] NOT NULL,
	[DDES_MCDE_SIR_ID] [smallint] NOT NULL,
	[DDES_MVAL_SIR_ID] [smallint] NOT NULL,
	[DDES_LLVR_SIR_ID] [smallint] NOT NULL,
	[DDES_SALES_PROD_AM] [money] NULL,
	[DDES_SALES_NON_PROD_AM] [money] NULL,
	[DDES_EAT_IN_TAC_QY] [smallint] NULL,
	[DDES_TAKE_OUT_TAC_QY] [smallint] NULL,
	[DDES_EAT_IN_SALES_AM] [money] NULL,
	[DDES_TAKE_OUT_SALES_AM] [money] NULL,
	[DDES_DISCOUNT_IN_TAC_QY] [smallint] NULL,
	[DDES_DISCOUNT_OUT_TAC_QY] [smallint] NULL,
	[DDES_DISCOUNT_IN_SALES_AM] [money] NULL,
	[DDES_DISCOUNT_OUT_SALES_AM] [money] NULL,
	[DDES_CREW_HOURS_WORKED] [numeric](12, 3) NULL,
	[DDES_PROCESS_DT] [datetime] NULL

);

