CREATE PROCEDURE [dbo].[sp_insert_ddhp_hourly_pmx]
    @list APP_DDAY_HOURLY_PMX_TYPE READONLY
AS
BEGIN
    -- Just return the items we passed in
    INSERT INTO APP_DDAY_HOURLY_PMX (DDHP_SITE_ID,  
DDHP_BUSINESS_DT ,
DDHP_PROD_ID,
DDHP_SALES_TM, 
DDHP_MCDE_SIR_ID,
DDHP_MVAL_SIR_ID,
DDHP_LLVR_SIR_ID,  
DDHP_EAT_IN_QY,  
DDHP_TAKE_OUT_QY,  
DDHP_PROMO_IN_QY,  
DDHP_PROMO_OUT_QY,  
DDHP_DISCOUNT_IN_QY,  
DDHP_DISCOUNT_OUT_QY,  
DDHP_EMPLOYEE_MEAL_QY,  
DDHP_MGR_MEAL_QY,  
DDHP_EMPLOYEE_MEAL_AM,  
DDHP_CA_IN_AM,  
DDHP_CA_OUT_AM,  
DDHP_PROCESS_DT)
    SELECT *
    FROM @list;
    
END