CREATE PROCEDURE [dbo].[SPW_INSERT_DDAY_HOURLY_PMX]
    @list APP_DDAY_HOURLY_PMX_TYPE READONLY
AS
BEGIN
 
    INSERT INTO APP_DDAY_HOURLY_PMX (DDMX_SITE_ID,  
DDMX_BUSINESS_DT ,
DDMX_PROD_ID,
DDMX_SALES_TM, 
DDMX_MCDE_SIR_ID,
DDMX_MVAL_SIR_ID,
DDMX_LLVR_SIR_ID,  
DDMX_EAT_IN_QY,  
DDMX_TAKE_OUT_QY,  
DDMX_PROMO_IN_QY,  
DDMX_PROMO_OUT_QY,  
DDMX_DISCOUNT_IN_QY,  
DDMX_DISCOUNT_OUT_QY,  
DDMX_EMPLOYEE_MEAL_QY,  
DDMX_MGR_MEAL_QY,  
DDMX_EMPLOYEE_MEAL_AM,  
DDMX_CA_IN_AM,  
DDMX_CA_OUT_AM,  
DDMX_PROCESS_DT)
    SELECT *
    FROM @list;
    
END