//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.App.GetXmlRpc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_HOURLY_SALES
    {
        public string HSA_CIE_ID { get; set; }
        public string HSA_SITE_ID { get; set; }
        public System.DateTime HSA_BUSINESS_DT { get; set; }
        public string HSA_SALES_TM { get; set; }
        public string HSA_MCDE_ID { get; set; }
        public string HSA_MVAL_ID { get; set; }
        public string HSA_LLVR_ID { get; set; }
        public string HSA_MPAY_ID { get; set; }
        public Nullable<decimal> HSA_SALES_PROD_AM { get; set; }
        public Nullable<decimal> HSA_SALES_NON_PROD_AM { get; set; }
        public Nullable<short> HSA_EAT_IN_TAC_QY { get; set; }
        public Nullable<short> HSA_TAKE_OUT_TAC_QY { get; set; }
        public Nullable<decimal> HSA_EAT_IN_SALES_AM { get; set; }
        public Nullable<decimal> HSA_TAKE_OUT_SALES_AM { get; set; }
        public Nullable<short> HSA_DISCOUNT_IN_TAC_QY { get; set; }
        public Nullable<short> HSA_DISCOUNT_OUT_TAC_QY { get; set; }
        public Nullable<decimal> HSA_DISCOUNT_IN_SALES_AM { get; set; }
        public Nullable<decimal> HSA_DISCOUNT_OUT_SALES_AM { get; set; }
        public Nullable<decimal> HSA_CREW_HOURS_WORKED { get; set; }
        public Nullable<decimal> HSA_CREW_GROSS_PAY { get; set; }
        public Nullable<System.DateTime> HSA_PROCESS_DT { get; set; }
        public string DTCE_ID { get; set; }
        public Nullable<decimal> HSA_HDVRY_COSTS_AM { get; set; }
    }
}
