//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.App.GetXmlRpc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_MVAL
    {
        public short MVAL_ID { get; set; }
        public short MVAL_SIR_ID { get; set; }
        public string MVAL_CD { get; set; }
        public string MVAL_NM { get; set; }
    }
}
