//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.App.GetXmlRpc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_SITE
    {
        public int SITE_ID { get; set; }
        public Nullable<int> SITE_REGN_ID { get; set; }
        public Nullable<int> SITE_BUDL_ID { get; set; }
        public Nullable<int> SITE_BUTP_ID { get; set; }
        public Nullable<int> SITE_HOZN_ID { get; set; }
        public Nullable<int> SITE_OPTR_ID { get; set; }
        public Nullable<int> SITE_DETP_ID { get; set; }
        public Nullable<int> SITE_COTN_ID { get; set; }
        public Nullable<int> SITE_JV_ID { get; set; }
        public Nullable<int> SITE_OPTP_ID { get; set; }
        public Nullable<int> SITE_GGCH_ID { get; set; }
        public Nullable<int> SITE_OPCH_ID { get; set; }
        public Nullable<int> SITE_MIZN_ID { get; set; }
        public Nullable<int> SITE_SPBX_ID { get; set; }
        public Nullable<int> SITE_SMHN_ID { get; set; }
        public Nullable<int> SITE_CTBX_ID { get; set; }
        public Nullable<int> SITE_ISTR_ID { get; set; }
        public Nullable<int> SITE_CMTP_ID { get; set; }
        public Nullable<int> SITE_PCTP_ADM_ID { get; set; }
        public Nullable<int> SITE_PCTP_OPS_ID { get; set; }
        public Nullable<int> SITE_CAOS_ID { get; set; }
        public Nullable<int> SITE_PRPE_ID { get; set; }
        public Nullable<int> SITE_OPPN_ID { get; set; }
        public Nullable<int> SITE_OSVS_ID { get; set; }
        public Nullable<int> SITE_PRINC_SITE_ID { get; set; }
        public Nullable<int> SITE_TEMP_ID { get; set; }
        public string SITE_TX { get; set; }
        public Nullable<System.DateTime> SITE_PLANNED_OPENING_DT { get; set; }
        public Nullable<System.DateTime> SITE_OPENING_DT { get; set; }
        public Nullable<System.DateTime> SITE_PERMANENT_CLOSURE_DT { get; set; }
        public Nullable<bool> SITE_DRIVE_BL { get; set; }
        public Nullable<short> SITE_ISD_INSIDE_SEAT_QY { get; set; }
        public Nullable<System.DateTime> SITE_ISD_INSIDE_SEAT_UPDATE_DT { get; set; }
        public Nullable<short> SITE_ISD_OUTSIDE_SEAT_QY { get; set; }
        public Nullable<System.DateTime> SITE_ISD_OUTSIDE_SEAT_UPDATE_DT { get; set; }
        public Nullable<short> SITE_INSIDE_SEAT_QY { get; set; }
        public Nullable<System.DateTime> SITE_INSIDE_SEAT_UPDATE_DT { get; set; }
        public Nullable<short> SITE_OUTSIDE_SEAT_QY { get; set; }
        public Nullable<System.DateTime> SITE_OUTSIDE_SEAT_UPDATE_DT { get; set; }
        public Nullable<short> SITE_MC_PARK_PLACE_QY { get; set; }
        public Nullable<System.DateTime> SITE_MC_PARK_PLACE_UPDATE_DT { get; set; }
        public Nullable<short> SITE_TOT_PARK_STALLS_QY { get; set; }
        public Nullable<System.DateTime> SITE_TOT_PARK_STALLS_UPDATE_DT { get; set; }
        public Nullable<decimal> SITE_SURFACE_AR { get; set; }
        public Nullable<System.DateTime> SITE_SURFACE_UPDATE_DT { get; set; }
        public Nullable<System.DateTime> SITE_DECO_TYPE_UPDATE_DT { get; set; }
        public Nullable<short> SITE_GROUP_CAPACITY_QY { get; set; }
        public byte[] SITE_PHOTO_BY { get; set; }
        public Nullable<System.DateTime> SITE_PHOTO_UPDATE_DT { get; set; }
        public Nullable<System.DateTime> SITE_LO_ORDER_PROPOSAL_BEGIN_DT { get; set; }
        public Nullable<bool> SITE_LO_HAPPY_MEAL_ORDER_PROPOSAL_BL { get; set; }
        public Nullable<bool> SITE_LO_BREAKFAST_BL { get; set; }
        public Nullable<bool> SITE_LO_STANDARD_KEYBOARD_BL { get; set; }
        public Nullable<short> SITE_EQ_CASH_REGISTER_QY { get; set; }
        public string SITE_EQ_OPS_ADDRESS_IP_TX { get; set; }
        public string SITE_EQ_ADMIN_ADDRESS_IP_TX { get; set; }
        public string SITE_EQ_ADMIN_PC_LOCALISATION_TX { get; set; }
        public Nullable<bool> SITE_EQ_MEMO_GARDE_CONTRACT_BL { get; set; }
        public string SITE_EQ_BBOX_ADDRESS_IP_TX { get; set; }
        public string SITE_EQ_COMMENT_CM { get; set; }
        public Nullable<bool> SITE_ALLIANCE_PRTNR_RESP_BL { get; set; }
        public Nullable<bool> SITE_ENTRY_WAY_RESP_BL { get; set; }
        public Nullable<bool> SITE_FRNT_CNTR_RESP_BL { get; set; }
        public Nullable<bool> SITE_REST_ROOM_RESP_BL { get; set; }
        public Nullable<bool> SITE_SEAT_AREA_RESP_BL { get; set; }
        public Nullable<bool> SITE_PARK_LOT_RESP_BL { get; set; }
        public Nullable<int> SITE_ALTN_ID { get; set; }
        public Nullable<int> SITE_DTMT_ID { get; set; }
        public string SITE_SHORT_TX { get; set; }
        public Nullable<int> SITE_BUDE_ID { get; set; }
        public string SITE_REF_INFO_NM { get; set; }
        public string SITE_GP_NM { get; set; }
        public Nullable<decimal> SITE_GEO_LAT { get; set; }
        public Nullable<decimal> SITE_GEO_LONG { get; set; }
        public string SITE_GEO_USERCHANGE_NM { get; set; }
        public Nullable<System.DateTime> SITE_GEO_UPDATE_DT { get; set; }
        public Nullable<System.DateTime> SITE_UPDATE_DT { get; set; }
        public string SITE_UPDATE_TYPE { get; set; }
    }
}
