//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.App.GetXmlRpc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_DDAY_HOURLY_PMX
    {
        public int DDHP_ID { get; set; }
        public short DDHP_SITE_ID { get; set; }
        public System.DateTime DDHP_BUSINESS_DT { get; set; }
        public int DDHP_PROD_ID { get; set; }
        public short DDHP_SALES_TM { get; set; }
        public byte DDHP_MCDE_SIR_ID { get; set; }
        public byte DDHP_MVAL_SIR_ID { get; set; }
        public byte DDHP_LLVR_SIR_ID { get; set; }
        public short DDHP_EAT_IN_QY { get; set; }
        public short DDHP_TAKE_OUT_QY { get; set; }
        public Nullable<short> DDHP_PROMO_IN_QY { get; set; }
        public Nullable<short> DDHP_PROMO_OUT_QY { get; set; }
        public Nullable<short> DDHP_DISCOUNT_IN_QY { get; set; }
        public Nullable<short> DDHP_DISCOUNT_OUT_QY { get; set; }
        public Nullable<short> DDHP_EMPLOYEE_MEAL_QY { get; set; }
        public Nullable<short> DDHP_MGR_MEAL_QY { get; set; }
        public Nullable<decimal> DDHP_EMPLOYEE_MEAL_AM { get; set; }
        public Nullable<decimal> DDHP_CA_IN_AM { get; set; }
        public Nullable<decimal> DDHP_CA_OUT_AM { get; set; }
        public System.DateTime DDHP_PROCESS_DT { get; set; }
    }
}
