//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.App.GetXmlRpc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_HOURLY_PMX
    {
        public byte PMXD_CIE_ID { get; set; }
        public byte PMXD_SITE_ID { get; set; }
        public System.DateTime PMXD_BUSINESS_DT { get; set; }
        public byte PMXD_PROD_ID { get; set; }
        public System.DateTime PMXD_SALES_TM { get; set; }
        public byte PMXD_MCDE_ID { get; set; }
        public byte PMXD_MVAL_ID { get; set; }
        public byte PMXD_LLVR_ID { get; set; }
        public short PMXD_EAT_IN_QY { get; set; }
        public short PMXD_TAKE_OUT_QY { get; set; }
        public Nullable<short> PMXD_PROMO_IN_QY { get; set; }
        public Nullable<short> PMXD_PROMO_OUT_QY { get; set; }
        public Nullable<short> PMXD_DISCOUNT_IN_QY { get; set; }
        public Nullable<short> PMXD_DISCOUNT_OUT_QY { get; set; }
        public Nullable<byte> PMXD_HOR_BL { get; set; }
        public Nullable<System.DateTime> PMXD_PROCESS_DT { get; set; }
        public Nullable<byte> PMXD_DTCE_ID { get; set; }
        public Nullable<decimal> PMXD_CA_IN_AM { get; set; }
        public Nullable<decimal> PMXD_CA_OUT_AM { get; set; }
    }
}
