//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.App.GetXmlRpc.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class McDashboardEntities : DbContext
    {
        public McDashboardEntities()
            : base("name=McDashboardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APP_HOURLY_PMX> APP_HOURLY_PMX { get; set; }
        public virtual DbSet<APP_HOURLY_SALES> APP_HOURLY_SALES { get; set; }
        public virtual DbSet<NP6XML> NP6XML { get; set; }
        public virtual DbSet<Log> Log { get; set; }
    }
}
