//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.App.GetXmlRpc.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class McDashboard_Entities : DbContext
    {
        public McDashboard_Entities()
            : base("name=McDashboard_RectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APP_DDAY_HOURLY_PMX> APP_DDAY_HOURLY_PMX { get; set; }
        public virtual DbSet<APP_DDAY_HOURLY_SALES> APP_DDAY_HOURLY_SALES { get; set; }
        public virtual DbSet<RFU_POD_SIR_ID> RFU_POD_SIR_ID { get; set; }
        public virtual DbSet<TRA_LOG> TRA_LOG { get; set; }
    
        public virtual int SPW_INSERT_DDAY_HOURLY_PMX()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPW_INSERT_DDAY_HOURLY_PMX");
        }
    
        public virtual int SPW_INSERT_DDAY_HOURLY_SALES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPW_INSERT_DDAY_HOURLY_SALES");
        }
    }
}
