//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.App.GetXmlRpc.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class McDashboardEntities : DbContext
    {
        public McDashboardEntities()
            : base("name=McDashboardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APP_DDAY_HOURLY_PMX> APP_DDAY_HOURLY_PMX { get; set; }
        public virtual DbSet<APP_DDAY_HOURLY_SALES> APP_DDAY_HOURLY_SALES { get; set; }
        public virtual DbSet<APP_HOURLY_PMX> APP_HOURLY_PMX { get; set; }
        public virtual DbSet<APP_HOURLY_SALES> APP_HOURLY_SALES { get; set; }
        public virtual DbSet<NP6XML> NP6XML { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
    }
}
