//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.App.GetXmlRpc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NP6XML
    {
        public int NumRestaurant { get; set; }
        public System.DateTime DayActivity { get; set; }
        public string HourlySales { get; set; }
        public string PMIX { get; set; }
        public Nullable<System.DateTime> HourlySalesDateMAJ { get; set; }
        public Nullable<System.DateTime> PmixDateMAJ { get; set; }
        public Nullable<System.DateTime> LastQueryHourlySales { get; set; }
        public Nullable<System.DateTime> LastQueryPMIX { get; set; }
    }
}
