//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.App.GetXmlRpc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NP6XML
    {
        public int NumRestaurant { get; set; }
        public System.DateTime DayActivity { get; set; }
        public string HourlySales { get; set; }
        public string PMIX { get; set; }
        public Nullable<System.DateTime> HourlySalesDateMAJ { get; set; }
        public Nullable<System.DateTime> PmixDateMAJ { get; set; }
        public Nullable<System.DateTime> LastQueryHourlySales { get; set; }
        public Nullable<System.DateTime> LastQueryPMIX { get; set; }
    }
}
