//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.App.GetXmlRpc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFA_POD_SIR_ID
    {
        public string PDID_PODSHORT { get; set; }
        public int PDID_MCDE_SIR_ID { get; set; }
        public int PDID_MVAL_SIR_ID { get; set; }
        public int PDID_LLVR_SIR_ID { get; set; }
    }
}
