//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.App.GetXmlRpc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFU_LLVR
    {
        public int LLVR_SIR_ID { get; set; }
        public string LLVR_PODSHORT { get; set; }
        public string LLVR_SIGNIFICATION { get; set; }
    }
}
