//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.App.GetXmlRpc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRA_LOG
    {
        public int LOG_ID { get; set; }
        public System.DateTime LOG_DATE { get; set; }
        public string LOG_RESTAURANTID { get; set; }
        public string LOG_DUREE { get; set; }
        public string LOG_THREAD { get; set; }
        public string LOG_LEVEL { get; set; }
        public string LOG_LOGGER { get; set; }
        public string LOG_MESSAGE { get; set; }
        public string LOG_PROCESSLOGID { get; set; }
        public string LOG_EXCEPTION { get; set; }
    }
}
