CREATE OR ALTER VIEW VW_CMU_DAILY_PMX(
    PRODUCT_CODE,
    SOLD_EAT_IN_QY,
    SOLD_TAKE_OUT_QY,
    PROMO_EAT_IN_QY,
    PROMO_TAKE_OUT_QY,
    DISCOUNT_EAT_IN_QY,
    DISCOUNT_TAKE_OUT_QY,
    WASTE_EAT_IN_QY,
    WASTE_TAKE_OUT_QY,
    MANAGER_MEAL_EAT_IN_QY,
    MANAGER_MEAL_TAKE_OUT_QY,
    CREW_MEAL_EAT_IN_QY,
    CREW_MEAL_TAKE_OUT_QY,
    EAT_IN_NET_AM,
    TAKE_OUT_NET_AM,
    TOTAL_TAX_AM)
AS
SELECT PRODUCT_CODE,
         SUM(SOLD_EAT_IN_QY),
         SUM(SOLD_TAKE_OUT_QY),
         SUM(PROMO_EAT_IN_QY),
         SUM(PROMO_TAKE_OUT_QY),
         SUM(DISCOUNT_EAT_IN_QY),
         SUM(DISCOUNT_TAKE_OUT_QY),
         SUM(WASTE_EAT_IN_QY),
         SUM(WASTE_TAKE_OUT_QY),
         SUM(MANAGER_EAT_IN_QY),
         SUM(MANAGER_TAKE_OUT_QY),
         SUM(CREW_EAT_IN_QY),
         SUM(CREW_TAKE_OUT_QY),
         SUM(EAT_IN_NET_AM),
         SUM(TAKE_OUT_NET_AM),
         SUM(TOTAL_TAX_AM)
    FROM VW_CMU_HOURLY_SALES_PMX
   WHERE POD_TYPE = 'ALL'
GROUP BY PRODUCT_CODE
;