
/* Table: CMU_PMIX_PRODUCT, Owner: SIRXP */

CREATE TABLE "CMU_PMIX_PRODUCT" 
(
  "BUSINESS_DATE"	DATE,
  "PRODUCT_ID"	INTEGER NOT NULL,
  "EAT_IN_PRICE"	NUMERIC(6, 2),
  "EAT_IN_TAX"	NUMERIC(6, 2),
  "TAKE_OUT_PRICE"	NUMERIC(6, 2),
  "TAKE_OUT_TAX"	NUMERIC(6, 2),
CONSTRAINT "PK_PMIX_PRODUCT" PRIMARY KEY ("PRODUCT_ID")
);
