/******************************************************************************/
/***               Generated by IBExpert 02/03/2021 16:49:24                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE CMU_HOURLY_SALES_PMX (
    BUSINESS_DATE        DATE,
    PRODUCT_CODE         INTEGER NOT NULL,
    QUARTER_TIME         TIMESTAMP NOT NULL,
    POD_TYPE             VARCHAR(5) NOT NULL,
    OPERATION_TYPE       VARCHAR(30) NOT NULL,
    EAT_IN_QY            INTEGER,
    TAKE_OUT_QY          INTEGER,
    EAT_IN_NET_AMOUNT    NUMERIC(10,2),
    TAKE_OUT_NET_AMOUNT  NUMERIC(10,2),
    NET_AMOUNT           NUMERIC(10,2),
    TAX_AMOUNT           NUMERIC(10,2)
);




/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON CMU_HOURLY_SALES_PMX TO SIRXP WITH GRANT OPTION;