
/* Table: CSHPMXJOUR, Owner: SIRXP */

CREATE TABLE "CSHPMXJOUR" 
(
  "CAL_DTACTIVITE"	DATE NOT NULL,
  "PRV_COD"	INTEGER NOT NULL,
  "PVJ_PRIXBRUTSP"	NUMERIC(6, 2),
  "PVJ_PRIXBRUTEMP"	NUMERIC(6, 2),
  "PVJ_PRIXNETSP"	NUMERIC(6, 2),
  "PVJ_PRIXNETEMP"	NUMERIC(6, 2),
  "PVJ_QTESP"	INTEGER,
  "PVJ_QTEEMP"	INTEGER,
  "PVJ_QTEPROMOS"	INTEGER,
  "PVJ_QTEPERTES"	INTEGER,
  "PVJ_QTEREPASEQP"	INTEGER,
  "PVJ_QTEREPASMGR"	INTEGER,
  "PVJ_MTREPASEMP"	NUMERIC(10, 2),
  "PVJ_QTEDISCOUNTSP"	INTEGER,
  "PVJ_QTEDISCOUNTEMP"	INTEGER,
  "PVJ_QTEDISCOUNT"	INTEGER,
  "PVJ_EAT_IN_NET_AM"	NUMERIC(8, 2),
  "PVJ_TAKE_OUT_NET_AM"	NUMERIC(8, 2),
  "PVJ_FLAGDFU"	CHAR(1),
  "PVJ_TOTAL_GROSS_AM"	NUMERIC(8, 2),
  "PVJ_QTE_PROMOS_FID"	INTEGER DEFAULT 0 NOT NULL,
CONSTRAINT "PK_CSHPMXJOUR" PRIMARY KEY ("PRV_COD", "CAL_DTACTIVITE")
);
ALTER TABLE "CSHPMXJOUR" ADD CONSTRAINT "FK_CSHPMXJO_HISTO_JOU_SYSCALEN" FOREIGN KEY ("CAL_DTACTIVITE") REFERENCES "SYSCALENDRIER" ("CAL_DTACTIVITE");
