COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* Stored procedures */

CREATE PROCEDURE "SPW_CMU_SavePMixProduct" 
(
  "DODELETE" SMALLINT,
  "BUSINESSDATE" DATE,
  "PRODUCTID" INTEGER,
  "EATINPRICE" NUMERIC(6, 2),
  "EATINTAX" NUMERIC(6, 2),
  "TAKEOUTPRICE" NUMERIC(6, 2),
  "TAKEOUTTAX" NUMERIC(6, 2)
)
AS
BEGIN EXIT; END ^


ALTER PROCEDURE "SPW_CMU_SavePMixProduct" 
(
  "DODELETE" SMALLINT,
  "BUSINESSDATE" DATE,
  "PRODUCTID" INTEGER,
  "EATINPRICE" NUMERIC(6, 2),
  "EATINTAX" NUMERIC(6, 2),
  "TAKEOUTPRICE" NUMERIC(6, 2),
  "TAKEOUTTAX" NUMERIC(6, 2)
)
AS
BEGIN
  IF (DoDelete = 1) THEN
  BEGIN
    DELETE FROM CMU_PMIX_PRODUCT;
  END

  DELETE FROM CMU_PMIX_PRODUCT
  WHERE
    (BUSINESS_DATE = :BusinessDate) AND (PRODUCT_ID = :ProductId);

  INSERT INTO CMU_PMIX_PRODUCT
  (
    BUSINESS_DATE, PRODUCT_ID,
    EAT_IN_PRICE, EAT_IN_TAX,
    TAKE_OUT_PRICE, TAKE_OUT_TAX
  )
  VALUES
  (
    :BusinessDate, :ProductId,
    :EatInPrice, :EatInTax,
    :TakeOutPrice, :TakeOutTax
  );
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
