use McDashboard_Rect
drop procedure SPW_INSERT_DDAY_HOURLY_PMX
go
CREATE PROCEDURE [dbo].[SPW_INSERT_DDAY_HOURLY_PMX]
    @list APP_DDAY_HOURLY_PMX_TYPE READONLY,
    @business_date datetime
AS
BEGIN
    DELETE FROM APP_DDAY_HOURLY_PMX WHERE DDHP_BUSINESS_DT=convert(varchar, @business_date, 101) and DDHP_SITE_ID =(select distinct DDHP_SITE_ID from @list)
    INSERT INTO APP_DDAY_HOURLY_PMX (DDHP_SITE_ID,  
DDHP_BUSINESS_DT ,
DDHP_PROD_ID,
DDHP_SALES_TM, 
DDHP_MCDE_SIR_ID,
DDHP_MVAL_SIR_ID,
DDHP_LLVR_SIR_ID,  
DDHP_EAT_IN_QY,  
DDHP_TAKE_OUT_QY,  
DDHP_PROMO_IN_QY,  
DDHP_PROMO_OUT_QY,  
DDHP_DISCOUNT_IN_QY,  
DDHP_DISCOUNT_OUT_QY,  
DDHP_EMPLOYEE_MEAL_QY,  
DDHP_MGR_MEAL_QY,  
DDHP_EMPLOYEE_MEAL_AM,  
DDHP_CA_IN_AM,  
DDHP_CA_OUT_AM,  
DDHP_PROCESS_DT)
    SELECT DDHP_SITE_ID,  
convert(varchar, @business_date, 101) ,
DDHP_PROD_ID,
DDHP_SALES_TM, 
DDHP_MCDE_SIR_ID,
DDHP_MVAL_SIR_ID,
DDHP_LLVR_SIR_ID,  
DDHP_EAT_IN_QY,  
DDHP_TAKE_OUT_QY,  
DDHP_PROMO_IN_QY,  
DDHP_PROMO_OUT_QY,  
DDHP_DISCOUNT_IN_QY,  
DDHP_DISCOUNT_OUT_QY,  
DDHP_EMPLOYEE_MEAL_QY,  
DDHP_MGR_MEAL_QY,  
DDHP_EMPLOYEE_MEAL_AM,  
DDHP_CA_IN_AM,  
DDHP_CA_OUT_AM,  
convert(varchar, getdate(), 121)
    FROM @list;
    
END